
pi_pins:
  # BCM pin number of the bottom right button.
  br_button_pin: 16

  # BCM pin for PWM brightness control of the screen.
  brightness_pin: 14

options:
  # Refresh rate in Hz.
  refresh_rate: 25

  # Screen horizontal resolution.
  h_res: 720

  # Screen vertical resolution.
  v_res: 480

can_info:
  # Can id that the compound messages are sent over.
  can_channel_id: 10

paths:
  # Default theme path.
  default_theme_path: "themes/default_theme.yaml"

  # Path to the night theme file.
  night_theme_path: "themes/night_theme.yaml"
