can_channels:
  - name: oil_pressure
    scaling_factor: 0.1
  - name: oil_temperature
    scaling_factor: 0.1
  - name: water_temperature
    scaling_factor: 0.1
  - name: fuel_pressure
    scaling_factor: 0.1
  - name: gear_position
    scaling_factor: 1
  - name: battery_voltage
    scaling_factor: 0.01
  - name: engine_rpm
    scaling_factor: 1

ui_elements:
  # - type: Background
  #   channel_name: engine_rpm
  #   imagePath: assets/wmf_wolf.png
  #   min_val: 11000
  #   max_val: 12500
  - type: bar_gauge
    channel_name: oil_pressure
    label: Oil P
    x_coord: 100
    y_coord: 150
    unit: PSI
    min_val: 0
    max_val: 300
  - type: bar_gauge
    channel_name: oil_temperature
    label: Oil T
    x_coord: 220
    y_coord: 150
    unit: F
    min_val: 0
    max_val: 250
  - type: bar_gauge
    channel_name: water_temperature
    label: Water T
    x_coord: 460
    y_coord: 150
    unit: F
    min_val: 0
    max_val: 220
  - type: bar_gauge
    channel_name: fuel_pressure
    label: Fuel P
    x_coord: 580
    y_coord: 150
    unit: PSI
    min_val: 0
    max_val: 500
  # - type: GearDisplay
  #   channel_name: gear_position
  # - type: VoltageBox
  #   channel_name: battery_voltage
  # - type: RPM_Display
  #   threshold_val: 10000
  #   max_val: 12500
  #   channel_name: engine_rpm
  # - type: DriverWarning
  #   channel_list: [battery_voltage]
  #   x_coord: 15
  #   y_coord: 160
  #   conditionals: ["battery_voltage < 12"]
  #   imagePath: assets/battery_warning.png
  # - type: DriverWarning
  #   channel_list: [oil_temperature]
  #   x_coord: 15
  #   y_coord: 240
  #   conditionals: ["oil_temperature > 100"]
  #   imagePath: assets/oil_temp_warning.png
  # - type: DriverWarning
  #   channel_list: [water_temperature]
  #   x_coord: 641
  #   y_coord: 160
  #   conditionals: ["water_temperature > 200"]
  #   imagePath: assets/water_temp_warning.png
  # - type: DriverWarning
  #   channel_list: [oil_pressure, engine_rpm]
  #   x_coord: 641
  #   y_coord: 240
  #   conditionals: ["oil_pressure > 200", "engine_rpm > 11000 critical"]
  #   imagePath: assets/generic_warning.png
element_config:
  bar_gauge:
    bar_width: 40
    bar_height: 200
    outline_width: 5
    text_size: 24
