can_channels:
  - name: oil_pressure
    scaling_factor: 0.1
  - name: oil_temperature
    scaling_factor: 0.1
  - name: water_temperature
    scaling_factor: 0.1
  - name: fuel_pressure
    scaling_factor: 0.1
  - name: gear_position
    scaling_factor: 1
  - name: battery_voltage
    scaling_factor: 0.01
  - name: engine_rpm
    scaling_factor: 1

ui_elements:
  # - type: Background
  #   channel_name: engine_rpm
  #   imagePath: assets/wmf_wolf.png
  #   min_val: 11000
  #   max_val: 12500
  - type: bar_gauge
    channel_name: oil_pressure
    label: Oil P
    x_coord: 100
    y_coord: 150
    unit: PSI
    min_val: 0
    max_val: 300
  - type: bar_gauge
    channel_name: oil_temperature
    label: Oil T
    x_coord: 220
    y_coord: 150
    unit: F
    min_val: 0
    max_val: 250
  - type: bar_gauge
    channel_name: water_temperature
    label: Water T
    x_coord: 460
    y_coord: 150
    unit: F
    min_val: 0
    max_val: 220
  - type: bar_gauge
    channel_name: fuel_pressure
    label: Fuel P
    x_coord: 580
    y_coord: 150
    unit: PSI
    min_val: 0
    max_val: 500
  - type: gear_display
    channel_name: gear_position
    min_val: 1
  - type: voltage_box
    channel_name: battery_voltage
    min_val: 0
  - type: rpm_display
    threshold_val: 10000
    min_val: 0
    max_val: 12500
    channel_name: engine_rpm
  - type: driver_warning
    channel_list: [battery_voltage]
    x_coord: 15
    y_coord: 160
    conditionals: ["battery_voltage < 12"]
    image_path: assets/battery_warning.png
  - type: driver_warning
    channel_list: [oil_temperature]
    x_coord: 15
    y_coord: 240
    conditionals: ["oil_temperature > 100"]
    image_path: assets/oil_temp_warning.png
  - type: driver_warning
    channel_list: [water_temperature]
    x_coord: 641
    y_coord: 160
    conditionals: ["water_temperature > 200"]
    image_path: assets/water_temp_warning.png
  - type: driver_warning
    channel_list: [oil_pressure, engine_rpm]
    x_coord: 641
    y_coord: 240
    conditionals: ["oil_pressure > 200", "engine_rpm > 11000 critical"]
    image_path: assets/generic_warning.png
element_config:
  bar_gauge:
    bar_width: 40
    bar_height: 200
    outline_width: 5
    text_size: 24
  gear_display:
    gear_size: 256
  voltage_box:
    border_thickness: 5
    text_size: 64
  rpm_display:
    text_size: 64
    vertical_pos: 10
  driver_warning:
    text_size: 14
    text_truncate_length: 9
